# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wikimedia Audience Stakeholder Framework
email: hello@reboot.org
description: > # this means to ignore newlines until "baseurl:"
  Who exactly is Wikimedia's audience, and where do they stack up?
baseurl: "https://thereboot.github.io/wmf-framework" # the subpath of your site, e.g. /blog
url: "https://thereboot.github.io/wmf-framework" # the base hostname & protocol for your site
twitter_username: theReboot
github_username:  theReboot

# Build settings
markdown: kramdown
